import java.util.ArrayList;
import java.util.List;
public class CountryNames{
  ArrayList<String> countryList = new ArrayList<>(List.of(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua & Barbuda",
            "Argentina ",
            "Armenia ",
            "Australia",
            "Austria ",
            "Azerbaijan ",
            "Bahamas ",
            "Bahrain ",
            "Bangladesh",
            "Barbados",
            "Belarus ",
            "Belgium",
            "Belize ",
            "Benin ",
            "Bhutan ",
            "Bolivia ",
            "Bosnia & Herzegovina",
            "Botswana ",
            "Brazil ",
            "Brunei ",
            "Bulgaria ",
            "Burkina Faso",
            "Burundi ",
            "Cambodia ",
            "Cameroon ",
            "Canada ",
            "Cape Verde",
            "Central African Republic",
            "Chad ",
            "Chile ",
            "China ",
            "Colombia ",
            "Comoros",
            "Congo",
            "Democratic Republic of the Congo",
            "Costa Rica ",
            "Côte d’Ivoire",
            "Croatia ",
            "Cuba ",
            "Cyprus ",
            "Czechia ",
            "Denmark ",
            "Djibouti ",
            "Dominican Republic",
            "East Timor",
            "Dominica ",
            "Ecuador",
            "Egypt ",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea ",
            "Estonia ",
            "Eswatini ",
            "Ethiopia ",
            "Fiji ",
            "Finland ",
            "France",
            "French Guiana",
            "Gabon",
            "Gambia ",
            "Georgia ",
            "Germany ",
            "Ghana ",
            "Greece ",
            "Greenland ",
            "Grenada ",
            "Guatemala ",
            "Guinea ",
            "Guyana ",
            "Guinea-bissau",
            "Haiti ",
            "Honduras ",
            "Hungary ",
            "Iceland ",
            "India ",
            "Indonesia ",
            "Iran ",
            "Iraq ",
            "Ireland ",
            "Italy ",
            "Jamaica ",
            "Japan ",
            "Jordan ",
            "Kazakhstan ",
            "Kenya ",
            "Kiribati ",
            "Kuwait ",
            "Kyrgyzstan ",
            "Laos ",
            "Latvia ",
            "Lebanon ",
            "Lesotho ",
            "Liberia ",
            "Libya ",
            "Liechtenstein ",
            "Lithuania ",
            "Luxembourg ",
            "Madagascar ",
            "Malawi ",
            "Malaysia",
            "Maldives ",
            "Mali ",
            "Malta ",
            "Marshall Islands",
            "Mauritania",
            "Mauritius ",
            "Mexico ",
            "Micronesia ",
            "Moldova ",
            "Monaco ",
            "Mongolia ",
            "Montenegro ",
            "Morocco ",
            "Mozambique ",
            "Myanmar ",
            "Namibia ",
            "Nauru ",
            "Nepal ",
            "Netherlands ",
            "New Zealand",
            "Nicaragua ",
            "Niger ",
            "Nigeria ",
            "North Korea",
            "North Macedonia",
            "Norway ",
            "Oman ",
            "Pakistan ",
            "Palau ",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay ",
            "Peru ",
            "Philippines ",
            "Poland ",
            "Portugal ",
            "Puerto Rico",
            "Qatar ",
            "Romania ",
            "Russia ",
            "Rwanda",
            "Samoa ",
            "San Marino",
            "São Tomé & Príncipe",
            "Saudi Arabia",
            "Senegal ",
            "Serbia ",
            "Seychelles ",
            "Sierra Leone",
            "Singapore ",
            "Slovakia",
            "Slovenia ",
            "Solomon Islands",
            "Somalia ",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain ",
            "Sri Lanka",
            "St. Lucia",
            "Sudan ",
            "Suriname ",
            "Sweden ",
            "Switzerland ",
            "Syria ",
            "Tajikistan ",
            "Tanzania ",
            "Thailand ",
            "Togo ",
            "Tonga ",
            "Tunisia ",
            "Turkey ",
            "Turkmenistan ",
            "Tuvalu ",
            "Uganda ",
            "Ukraine ",
            "United Arab Emirates ",
            "United Kingdom",
            "United States",
            "Uruguay ",
            "Uzbekistan",
            "Vatican ",
            "Vietnam ",
            "Western Sahara",
            "Yemen ",
            "Zambia",
            "Zimbabwe"
    ));
  public ArrayList<String> getCountryNames(){
    return countryList;
  }
}
